# Generated by Django 2.2.6 on 2020-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='cover'),
        ),
    ]
