# Generated by Django 2.2.6 on 2020-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200517_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/moviecovers', verbose_name='cover'),
        ),
    ]
