# Generated by Django 2.2.6 on 2020-05-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200517_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(null=True, upload_to='moviecovers', verbose_name='cover'),
        ),
    ]
