# Generated by Django 2.2.6 on 2020-05-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200518_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(null=True, verbose_name='release date'),
        ),
    ]
