# Generated by Django 2.2.6 on 2020-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200520_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directed_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
